services:
  webapp:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
        - ./src:/src
    environment:
      - DB_HOST=db
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpassword
    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
